server {
    listen 8080;
    root /usr/share/nginx/html;
    index login.html;

    location / {
        try_files $uri $uri/ /login.html;
    }

    location /pages/ {
        try_files $uri /login.html;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript;
}
